services:
  fitzza-frontend:
    image: uniquecolor/fitzza-frontend:development
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fitzza-frontend
    ports:
      - "80:80"
    restart: unless-stopped
    environment:
      - NODE_ENV=production